// <auto-generated />
using System;
using AidatTakipSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AidatTakipSistemi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251030201637_IlkKurulum")]
    partial class IlkKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AidatTakipSistemi.Models.Aidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaireId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Donem")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OdendiMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SonOdemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DaireId");

                    b.ToTable("Aidatlar");
                });

            modelBuilder.Entity("AidatTakipSistemi.Models.Daire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Blok")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DaireNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SahipAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SakinAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Daireler");
                });

            modelBuilder.Entity("AidatTakipSistemi.Models.Odeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AidatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OdenenTutar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AidatId");

                    b.ToTable("Odemeler");
                });

            modelBuilder.Entity("AidatTakipSistemi.Models.Aidat", b =>
                {
                    b.HasOne("AidatTakipSistemi.Models.Daire", "Daire")
                        .WithMany()
                        .HasForeignKey("DaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Daire");
                });

            modelBuilder.Entity("AidatTakipSistemi.Models.Odeme", b =>
                {
                    b.HasOne("AidatTakipSistemi.Models.Aidat", "Aidat")
                        .WithMany()
                        .HasForeignKey("AidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aidat");
                });
#pragma warning restore 612, 618
        }
    }
}
